Repository supitsdu/clipper, pull requests merged in 2024-06, with the labels that each got.

#3 feat: add custom usage message for clipper tool
  main.go
Labels: enhancement

#4 feat: add version flag to display current version of clipper
  main.go
Labels: enhancement

#5 refactor: extract file and stdin reading into separate functions
  main.go
  main_test.go
Labels: enhancement

#7 feat(makefile): include version in binary filenames and more improvements
  makefile
Labels: feature, build

#8 build(ci/cd): create Go workflow to build and test clipper
  .github/workflows/go.yml
Labels: build

#9 fix: add way to skip clipboard tests when on CI/CD workflows
  .github/workflows/go.yml
  main_test.go
Labels: bug, build

#10 feat: add installation script for Clipper
  install.sh
Labels: feature

#11 docs: update README to include installation via install.sh script
  README.md
Labels: documentation

#12 docs: Update README.md
  README.md
Labels: documentation

#13 feat: add support for copying multiple files to clipboard
  main.go
Labels: feature

#16 refactor: improved readability in parsetContent()
  main.go
Labels: refactoring

#17 test: add unit tests for content parsing and input reading
  main_test.go
Labels: test

#18 feat: smarter installation script for Clipper
  install.sh
Labels: installation

#19 test: enhance parseContent tests with large file handling and more
  go.mod
  go.sum
  main_test.go
Labels: test, refactoring, under review

#21 refact(tests): improves handling of cleanup func
  main_test.go
Labels: test, refactoring

#29 refactor: updates Package Structure, Add Interfaces, and Enhance Testing
  cli/clipper/clipper.go
  cli/main.go
  cli/options/options.go
  main.go
  main_test.go
  makefile
  tests/clipper_test.go
Labels: enhancement, test, refactoring, under review, cleanup

#32 ci: Add golangci-lint configuration and fix initial linting errors
  .golangci.yaml
  cli/clipper/clipper.go
  tests/clipper_test.go
Labels: cleanup, CI CD

#34 feat(clipper): Implement concurrent file reading and refactor project structure
  cli/clipper/clipper.go
  cli/reader/reader.go
  tests/clipper/clipper_test.go
  tests/reader/reader_test.go
  tests/tests.go
Labels: enhancement, refactoring, performance, concurrency

#35 fix: Prevent unexpected newline in output for empty files
  cli/reader/reader.go
  tests/reader/reader_test.go
Labels: enhancement, cleanup

#37 refactor(clipper/options): Enhance version handling and remove pointers for improved usability
  cli/clipper/clipper.go
  cli/main.go
  cli/options/options.go
  cli/reader/reader.go
  makefile
  tests/reader/reader_test.go
Labels: enhancement, refactoring, cleanup, usability
